refactor: move to Cloudflare workers
DTrombett/ms-bot pull request #584
Opened 2023-12-26 18:00 UTC by DTrombett

**Changes this PR makes:**

It seems that replit will drop free hosting for discord bots. This means that it's time to move on!
I chose to try moving to Cloudflare Workers because they ~~have a free plan~~ are blazingly fast, have nearly no downtime and it is an opportunity to try the discord interactions via webhook.
This, sadly, has some disadvantages too because it makes difficult for us to implement the `/remind me` command and, mostly, the predictions logic.
However, I like tricky things, so this is where we're going! I'll be migrating all the commands, one by one, leaving the remind (probably, we'll need to drop it) and the predictions ones to the end.

PS: I'll probably ask @NotReallyEight to help me migrating some commands to conclude earlier 😁

2024-01-05 13:26 UTC, DTrombett commented
Not really ready but I need a review anyway

2024-01-05 14:16 UTC, NotReallyEight commented
holy moly

2024-01-05 14:39 UTC, NotReallyEight requested changes

2024-01-05 14:39 UTC, NotReallyEight commented on wrangler.toml
No trailing white space here

2024-01-05 14:52 UTC, DTrombett commented on wrangler.toml
What

2024-01-05 14:54 UTC, NotReallyEight commented on wrangler.toml
![image](https://github.com/DTrombett/ms-bot/assets/71493060/06e75716-f7c8-49f1-a201-5b58e991b8be)

2024-01-18 12:58 UTC, NotReallyEight approved these changes
LGTM.

2024-06-09 16:55 UTC, merged